"""legislator photos and offices

Revision ID: 0b8c8d6190a5
Revises: 623abf34a41b
Create Date: 2026-10-06 01:01:56.924567

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0b8c8d6190a5'
down_revision: str | Sequence[str] | None = '623abf34a41b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('legislators', sa.Column('state_name', sa.String(length=50), nullable=True))
    op.add_column('legislators', sa.Column('image_url', sa.Text(), nullable=True))
    op.add_column('legislators', sa.Column('image_credit', sa.String(length=255), nullable=True))
    op.add_column('legislators', sa.Column('career', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('legislators', sa.Column('office_address', sa.Text(), nullable=True))
    op.add_column('legislators', sa.Column('phone', sa.String(length=30), nullable=True))
    op.add_column('legislators', sa.Column('member_synced_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_legislators_member_synced_at'), 'legislators', ['member_synced_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_legislators_member_synced_at'), table_name='legislators')
    op.drop_column('legislators', 'member_synced_at')
    op.drop_column('legislators', 'phone')
    op.drop_column('legislators', 'office_address')
    op.drop_column('legislators', 'career')
    op.drop_column('legislators', 'image_credit')
    op.drop_column('legislators', 'image_url')
    op.drop_column('legislators', 'state_name')
    # ### end Alembic commands ###
