"""legislators and cosponsors

Revision ID: 623abf34a41b
Revises: 4522f54172b7
Create Date: 2026-10-06 00:46:08.537154

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '623abf34a41b'
down_revision: str | Sequence[str] | None = '4522f54172b7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legislators',
    sa.Column('bioguide_id', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('party', sa.String(length=5), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('district', sa.Integer(), nullable=True),
    sa.Column('chamber', sa.String(length=10), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('bioguide_id')
    )
    op.create_table('bill_cosponsors',
    sa.Column('bill_id', sa.UUID(), nullable=False),
    sa.Column('bioguide_id', sa.String(length=20), nullable=False),
    sa.Column('is_original', sa.Boolean(), nullable=False),
    sa.Column('sponsorship_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['bioguide_id'], ['legislators.bioguide_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bill_id', 'bioguide_id')
    )
    op.create_index(op.f('ix_bill_cosponsors_bioguide_id'), 'bill_cosponsors', ['bioguide_id'], unique=False)
    op.add_column('bills', sa.Column('cosponsor_count', sa.Integer(), server_default='0', nullable=False))
    op.create_index(op.f('ix_bills_sponsor_id'), 'bills', ['sponsor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bills_sponsor_id'), table_name='bills')
    op.drop_column('bills', 'cosponsor_count')
    op.drop_index(op.f('ix_bill_cosponsors_bioguide_id'), table_name='bill_cosponsors')
    op.drop_table('bill_cosponsors')
    op.drop_table('legislators')
    # ### end Alembic commands ###
