"""follows, home district, roster, full-text search

Revision ID: b8f77e6221b8
Revises: 387b044fc971
Create Date: 2026-10-08 18:16:04.531053

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b8f77e6221b8'
down_revision: str | Sequence[str] | None = '387b044fc971'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bill_follows',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('bill_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'bill_id')
    )
    op.create_index(op.f('ix_bill_follows_bill_id'), 'bill_follows', ['bill_id'], unique=False)
    op.create_table('district_follows',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('district', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'state', 'district')
    )
    op.create_table('legislator_follows',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('bioguide_id', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bioguide_id'], ['legislators.bioguide_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'bioguide_id')
    )
    op.create_index(op.f('ix_legislator_follows_bioguide_id'), 'legislator_follows', ['bioguide_id'], unique=False)
    op.add_column('bills', sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("setweight(to_tsvector('english'::regconfig, coalesce(title, '')), 'A') || setweight(to_tsvector('english'::regconfig, coalesce(summary_simple, '') || ' ' || coalesce(summary_detailed, '')), 'B') || setweight(to_tsvector('english'::regconfig, left(coalesce(full_text, ''), 300000)), 'C')", persisted=True), nullable=False))
    op.create_index('ix_bills_search_vector', 'bills', ['search_vector'], unique=False, postgresql_using='gin')
    op.add_column('legislators', sa.Column('in_office', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('home_state', sa.String(length=2), nullable=True))
    op.add_column('users', sa.Column('home_district', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'home_district')
    op.drop_column('users', 'home_state')
    op.drop_column('legislators', 'in_office')
    op.drop_index('ix_bills_search_vector', table_name='bills', postgresql_using='gin')
    op.drop_column('bills', 'search_vector')
    op.drop_index(op.f('ix_legislator_follows_bioguide_id'), table_name='legislator_follows')
    op.drop_table('legislator_follows')
    op.drop_table('district_follows')
    op.drop_index(op.f('ix_bill_follows_bill_id'), table_name='bill_follows')
    op.drop_table('bill_follows')
    # ### end Alembic commands ###
